"use client"

import { createContext, useContext, useState, useEffect, ReactNode } from "react"

type Language = "fr" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.about": "A propos",
    "nav.projects": "Projets",
    "nav.openMenu": "Ouvrir le menu",
    "nav.closeMenu": "Fermer le menu",
    
    // Home Page
    "home.badge": "Portfolio 2025",
    "home.title": "Aurélie Perichon",
    "home.subtitle": "Étudiante en MSc AI Applied to Business",
    "home.description": "Passionnee par l'analyse de donnees au service de la strategie et de l'innovation. Je combine expertise technique et vision business pour creer des solutions impactantes.",
    "home.cta": "Decouvrir mes projets",
    "home.projectsTitle": "Mes Projets",
    "home.projectsDescription": "Decouvrez mes realisations a travers des experiences interactives uniques. Chaque projet raconte une histoire differente.",
    "home.explore": "Explorer",
    "home.stat.projects": "Projets realises",
    "home.stat.tech": "Technologies",
    "home.stat.degree": "Formation en cours",
    "home.stat.experience": "Experience retail",
    
    // Project Cards
    "project.marioKart.title": "Mario Kart",
    "project.marioKart.tagline": "Web scraping des records mondiaux de Mario Kart 8. Extraction et analyse de donnees de performance.",
    "project.zigzag.title": "ZigZag",
    "project.zigzag.tagline": "Jeu multijoueur en ligne ou les messages se transforment. Experience temps reel avec authentification.",
    "project.synapse.title": "Synapse",
    "project.synapse.tagline": "Chatbot RAG pour la recherche scientifique. Acces a 182K+ theses francaises avec citations.",
    "project.eugenia.title": "Eugenia School",
    "project.eugenia.tagline": "Optimisation SEO et GEO du site web officiel d'Eugenia School. React, Vite, Tailwind CSS.",
    "project.supplyBrain.title": "Supply Brain - Hackathon Mirakl",
    "project.supplyBrain.tagline": "Dashboard d'intelligence supply chain avec agents IA integres. Analyse ventes, stocks et CO2.",
    
    // Eugenia School Page
    "eugenia.badge": "SEO / GEO",
    "eugenia.title": "Eugenia School",
    "eugenia.subtitle": "Optimisation SEO et GEO du site web",
    "eugenia.description": "Refonte complete du site officiel d'Eugenia School, ecole superieure specialisee dans l'IA et le Business. Optimisation pour les moteurs de recherche et la geolocalisation.",
    "eugenia.viewSite": "Voir le site",
    "eugenia.viewGithub": "Voir sur GitHub",
    "eugenia.section.overview": "Apercu",
    "eugenia.section.stack": "Stack Technique",
    "eugenia.section.features": "Fonctionnalites",
    "eugenia.section.structure": "Structure",
    "eugenia.overview.title": "Site Web Moderne",
    "eugenia.overview.description": "Developpement d'un site web complet pour une ecole superieure avec un focus sur l'experience utilisateur, le SEO et les performances.",
    "eugenia.overview.detail1": "Design responsive et moderne avec Tailwind CSS",
    "eugenia.overview.detail2": "Optimisation SEO complete (meta tags, sitemap, schema.org)",
    "eugenia.overview.detail3": "Integration GEO pour la localisation du campus",
    "eugenia.stack.framework": "Framework",
    "eugenia.stack.routing": "Routing",
    "eugenia.stack.styling": "Styling",
    "eugenia.stack.state": "State",
    "eugenia.features.title": "Fonctionnalites Cles",
    "eugenia.features.responsive": "Design Responsive",
    "eugenia.features.seo": "SEO Optimise",
    "eugenia.features.forms": "Formulaires de candidature",
    "eugenia.features.blog": "Blog dynamique",
    "eugenia.features.faq": "FAQ interactive",
    "eugenia.features.campus": "Pages campus",
    "eugenia.structure.title": "Structure du Site",
    "eugenia.structure.pages": "Plus de 20 pages optimisees",
    "eugenia.colors": "Direction Artistique",
    "eugenia.colors.primary": "Rose/Bordeaux",
    "eugenia.colors.accent": "Jaune Eugenia",
    "eugenia.colors.bg": "Cream / Blanc",
    
    // Supply Brain Page
    "supply.badge": "Dashboard IA",
    "supply.title": "Supply Brain",
    "supply.subtitle": "Intelligence Supply Chain avec Agents IA",
    "supply.description": "Dashboard d'analyse en temps reel pour l'ecosysteme Mirakl Connect. Ventes, stocks, CO2 et previsions avec 6 agents IA specialises.",
    "supply.viewDemo": "Voir la demo",
    "supply.viewGithub": "Voir sur GitHub",
    "supply.section.overview": "Apercu",
    "supply.section.agents": "Agents IA",
    "supply.section.stack": "Architecture",
    "supply.section.features": "Fonctionnalites",
    "supply.overview.title": "Dashboard Temps Reel",
    "supply.overview.description": "Plateforme complete d'intelligence supply chain avec analyse predictive et agents IA conversationnels.",
    "supply.overview.detail1": "6 agents IA specialises (Dust.tt) pour analyse multi-domaine",
    "supply.overview.detail2": "NL2SQL : questions en langage naturel vers requetes SQL",
    "supply.overview.detail3": "Visualisations interactives (Recharts, Leaflet)",
    "supply.agents.title": "6 Agents IA Specialises",
    "supply.agents.monitoring": "Monitoring",
    "supply.agents.monitoring.desc": "Analyse ventes et tendances marketplace",
    "supply.agents.supply": "Supply Allocation",
    "supply.agents.supply.desc": "Analyse ABC, concentration HHI",
    "supply.agents.pricing": "Pricing Adjustment",
    "supply.agents.pricing.desc": "Rotation stock, DSI, dormants",
    "supply.agents.eco": "EcoFlow Analyst",
    "supply.agents.eco.desc": "Empreinte CO2, score logistique",
    "supply.agents.predictive": "IA Predictive",
    "supply.agents.predictive.desc": "Previsions rupture, alertes",
    "supply.agents.orchestrator": "Orchestrateur",
    "supply.agents.orchestrator.desc": "Delegation multi-agents",
    "supply.stack.title": "Architecture Technique",
    "supply.stack.frontend": "Frontend",
    "supply.stack.backend": "Backend / Services",
    "supply.stack.database": "Base de donnees",
    "supply.features.title": "Vues Dashboard",
    "supply.features.overview": "Vue Overview",
    "supply.features.products": "Vue Products",
    "supply.features.financial": "Vue Financial",
    "supply.features.sustainability": "Vue Sustainability",
    "supply.features.predictive": "Vue Predictive",
    "supply.features.analysis": "Vue AI Analysis",
    
    // Mario Kart Page
    "mario.badge": "Projet Data",
    "mario.title": "Mario Kart World Records",
    "mario.description": "Controlez la voiture avec les fleches ou en cliquant pour decouvrir le projet de web scraping des records mondiaux de Mario Kart 8",
    "mario.startRace": "Commencer la course",
    "mario.restart": "Recommencer",
    "mario.continue": "Continuer",
    "mario.finish": "Arrivee",
    "mario.controls": "Controles",
    "mario.controlsDesc": "Fleches gauche/droite ou cliquez sur les cotes",
    "mario.checkpoint.context": "Contexte",
    "mario.checkpoint.demo": "Demo",
    "mario.checkpoint.presentation": "Presentation",
    "mario.context.title": "Web Scraping Mario Kart 8",
    "mario.context.description": "Extraction et analyse des records mondiaux de Mario Kart 8 depuis le site Mario Kart World Records.",
    "mario.context.detail1": "Scraping des temps records sur toutes les pistes",
    "mario.context.detail2": "Extraction des donnees joueurs, vehicules et configurations",
    "mario.context.detail3": "Objectif : Identifier les meilleures meta et strategies competitives",
    "mario.demo.title": "Demo du Scraping",
    "mario.demo.description": "Cette video montre le processus de scraping en action. Le script extrait les donnees et genere un fichier CSV contenant toutes les informations nettoyees et structurees.",
    "mario.demo.csvOutput": "Export CSV avec donnees nettoyees",
    "mario.presentation.title": "Presentation du Projet",
    "mario.presentation.description": "Decouvrez l'analyse complete des donnees, les insights et les resultats dans la presentation Canva.",
    "mario.presentation.view": "Voir la presentation",
    "mario.tech.title": "Stack Technique",
    "mario.tech.used": "Technologies utilisees",
    "mario.tech.files": "Fichiers principaux",
    "mario.results.title": "Resultats du Projet",
    "mario.results.execTime": "Temps d'execution",
    "mario.results.dataExtracted": "Donnees extraites",
    "mario.results.realtime": "Temps reel",
    "mario.sourceCode": "Code source",
    "mario.viewResults": "Voir les resultats",
    "mario.raceComplete": "Course terminee !",
    "mario.raceCompleteDesc": "Vous avez decouvert tous les aspects du projet Mario Kart World Records",
    "mario.viewGithub": "Voir sur GitHub",
    "mario.replay": "Rejouer",
    
    // ZigZag Page
    "zigzag.badge": "Mini-Jeu Dessin",
    "zigzag.title": "ZigZag",
    "zigzag.description": "Reproduisez les dessins pour decouvrir le projet ! Inspiré de Gartic Phone, dessinez et passez au niveau suivant.",
    "zigzag.level": "Niveau",
    "zigzag.tutorial": "Tutoriel",
    "zigzag.intermediate": "Intermediaire",
    "zigzag.challenger": "Challenger",
    "zigzag.play": "Commencer",
    "zigzag.restart": "Recommencer",
    "zigzag.clear": "Effacer",
    "zigzag.submit": "Valider",
    "zigzag.drawThis": "Dessinez ceci :",
    "zigzag.yourDrawing": "Votre dessin :",
    "zigzag.wellDone": "Bien joue !",
    "zigzag.levelComplete": "Niveau {level} complete !",
    "zigzag.nextLevel": "Niveau suivant",
    "zigzag.replay": "Rejouer",
    "zigzag.projectLinks": "Liens du projet",
    "zigzag.playOnSite": "Jouer sur zig-zag.fun",
    "zigzag.viewSource": "Voir le code source",
    "zigzag.progress": "Progression",
    "zigzag.info1.title": "ZigZag - Jeu de Dessin Multijoueur",
    "zigzag.info1.description": "Jeu multijoueur en ligne inspire de Gartic Phone. Les joueurs dessinent et devinent en chaine pour des moments de fun garantis !",
    "zigzag.info2.title": "Stack Technique",
    "zigzag.info2.description": "Application moderne avec authentification Google OAuth et synchronisation temps reel via Supabase.",
    "zigzag.info3.title": "Fonctionnalites",
    "zigzag.info3.description": "Experience complete avec lobbies, tours de jeu, et galerie des dessins. Deploye en production.",
    "zigzag.technologies": "Technologies",
    "zigzag.features": "Fonctionnalites",
    "zigzag.realtime": "Temps reel",
    "zigzag.auth": "OAuth Google",
    "zigzag.deployed": "Deploye sur zig-zag.fun",
    
    // Synapse Page
    "synapse.badge": "Chatbot RAG",
    "synapse.title": "Synapse",
    "synapse.subtitle": "Chatbot RAG pour la Recherche Scientifique",
    "synapse.description": "Communication entre donnees et intelligence artificielle. Explorez 182K+ theses francaises avec des questions/reponses contextuelles.",
    "synapse.viewGithub": "Voir sur GitHub",
    "synapse.explore": "Explorer",
    "synapse.openBook": "Ouvrir le livre",
    "synapse.page": "Page",
    "synapse.nextPage": "Page suivante",
    "synapse.prevPage": "Page precedente",
    "synapse.closeBook": "Fermer le livre",
    "synapse.featuresTitle": "Fonctionnalites",
    "synapse.featuresSubtitle": "Trois piliers pour une recherche intelligente",
    "synapse.feature1.title": "Recherche HAL",
    "synapse.feature1.description": "Acces a 182K+ theses francaises via l'API HAL",
    "synapse.feature2.title": "Chat RAG",
    "synapse.feature2.description": "Questions/Reponses contextuelles avec citations",
    "synapse.feature3.title": "ML Features",
    "synapse.feature3.description": "Classification, resumes, recommandations",
    "synapse.stackTitle": "Stack Technique",
    "synapse.stackSubtitle": "Technologies modernes pour une architecture robuste",
    "synapse.backend": "Backend",
    "synapse.frontend": "Frontend",
    "synapse.database": "Base de donnees",
    "synapse.pipelineTitle": "Pipeline RAG",
    "synapse.pipelineSubtitle": "De la question a la reponse contextualisee",
    "synapse.pipeline.request": "Requete",
    "synapse.pipeline.api": "HAL API",
    "synapse.pipeline.extraction": "Extraction PDF",
    "synapse.pipeline.vectorization": "Vectorisation",
    "synapse.pipeline.chat": "Chat",
    "synapse.pipeline.response": "Reponse",
    "synapse.ctaTitle": "Explorez le projet",
    "synapse.ctaDescription": "Decouvrez le code source, la documentation et contribuez au developpement de Synapse sur GitHub.",
    
    // About Page
    "about.badge": "A propos",
    "about.title": "Aurelie Perichon",
    "about.subtitle": "Profil business et technique en IA et data, je conçois des solutions qui rendent l’analyse plus claire, automatisent les tâches utiles et soutiennent la décision.",
    "about.contact": "Contact",
    "about.languages": "Langues",
    "about.french": "Francais",
    "about.english": "Anglais",
    "about.native": "Natif",
    "about.interests": "Centres d'interet",
    "about.interest.gaming": "Jeux video",
    "about.interest.singing": "Chant",
    "about.interest.asian": "Culture asiatique",
    "about.interest.climbing": "Escalade",
    "about.interest.dance": "Danse",
    "about.interest.travel": "Voyage",
    "about.profile": "Profil",
    "about.profileText": "Profil business et technique en IA et data, je conçois des solutions qui rendent l’analyse plus claire, automatisent les tâches utiles et soutiennent la décision.",
    "about.education": "Formation",
    "about.current": "En cours",
    "about.experience": "Expérience",
    "about.skills": "Compétences",
    "about.ctaTitle": "Interesse(e) par mon profil ?",
    "about.ctaDescription": "N'hesitez pas a me contacter pour discuter de projets ou opportunites.",
    "about.contactMe": "Me contacter",
    
    // Footer
    "footer.description": "Etudiante en MSc AI Applied to Business, passionnee par l'analyse de donnees au service de la strategie et de l'innovation.",
    "footer.projects": "Projets",
    "footer.contact": "Contact",
    "footer.rights": "Tous droits reserves.",
    "footer.supplyBrain": "Supply Brain - Hackathon Mirakl",
    "footer.synapse": "Synapse - Chatbot RAG",
    "footer.eugenia": "Eugenia School - SEO/GEO",
    "footer.zigzag": "ZigZag - Mini-Jeu",
    "footer.marioKart": "Mario Kart - Web Scraping",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.projects": "Projects",
    "nav.openMenu": "Open menu",
    "nav.closeMenu": "Close menu",
    
    // Home Page
    "home.badge": "Portfolio 2025",
    "home.title": "Aurélie Perichon",
    "home.subtitle": "MSc AI Applied to Business Student",
    "home.description": "Passionate about data analysis to drive strategy and innovation. I combine technical expertise and business vision to create impactful solutions.",
    "home.cta": "Discover my projects",
    "home.projectsTitle": "My Projects",
    "home.projectsDescription": "Explore my work through unique interactive experiences. Each project tells a different story.",
    "home.explore": "Explore",
    "home.stat.projects": "Projects completed",
    "home.stat.tech": "Technologies",
    "home.stat.degree": "Ongoing degree",
    "home.stat.experience": "Retail experience",
    
    // Project Cards
    "project.marioKart.title": "Mario Kart",
    "project.marioKart.tagline": "Web scraping of Mario Kart 8 world records. Performance data extraction and analysis.",
    "project.zigzag.title": "ZigZag",
    "project.zigzag.tagline": "Online multiplayer game where messages transform. Real-time experience with authentication.",
    "project.synapse.title": "Synapse",
    "project.synapse.tagline": "RAG Chatbot for scientific research. Access to 182K+ French theses with citations.",
    "project.eugenia.title": "Eugenia School",
    "project.eugenia.tagline": "SEO and GEO optimization of Eugenia School official website. React, Vite, Tailwind CSS.",
    "project.supplyBrain.title": "Supply Brain - Mirakl Hackathon",
    "project.supplyBrain.tagline": "Supply chain intelligence dashboard with integrated AI agents. Sales, stock and CO2 analysis.",
    
    // Eugenia School Page
    "eugenia.badge": "SEO / GEO",
    "eugenia.title": "Eugenia School",
    "eugenia.subtitle": "SEO and GEO Website Optimization",
    "eugenia.description": "Complete redesign of Eugenia School official website, a higher education school specialized in AI and Business. Optimization for search engines and geolocation.",
    "eugenia.viewSite": "View site",
    "eugenia.viewGithub": "View on GitHub",
    "eugenia.section.overview": "Overview",
    "eugenia.section.stack": "Tech Stack",
    "eugenia.section.features": "Features",
    "eugenia.section.structure": "Structure",
    "eugenia.overview.title": "Modern Website",
    "eugenia.overview.description": "Development of a complete website for a higher education school with focus on user experience, SEO and performance.",
    "eugenia.overview.detail1": "Responsive and modern design with Tailwind CSS",
    "eugenia.overview.detail2": "Complete SEO optimization (meta tags, sitemap, schema.org)",
    "eugenia.overview.detail3": "GEO integration for campus localization",
    "eugenia.stack.framework": "Framework",
    "eugenia.stack.routing": "Routing",
    "eugenia.stack.styling": "Styling",
    "eugenia.stack.state": "State",
    "eugenia.features.title": "Key Features",
    "eugenia.features.responsive": "Responsive Design",
    "eugenia.features.seo": "SEO Optimized",
    "eugenia.features.forms": "Application forms",
    "eugenia.features.blog": "Dynamic blog",
    "eugenia.features.faq": "Interactive FAQ",
    "eugenia.features.campus": "Campus pages",
    "eugenia.structure.title": "Site Structure",
    "eugenia.structure.pages": "More than 20 optimized pages",
    "eugenia.colors": "Art Direction",
    "eugenia.colors.primary": "Pink/Burgundy",
    "eugenia.colors.accent": "Eugenia Yellow",
    "eugenia.colors.bg": "Cream / White",
    
    // Supply Brain Page
    "supply.badge": "AI Dashboard",
    "supply.title": "Supply Brain",
    "supply.subtitle": "Supply Chain Intelligence with AI Agents",
    "supply.description": "Real-time analytics dashboard for Mirakl Connect ecosystem. Sales, inventory, CO2 and forecasting with 6 specialized AI agents.",
    "supply.viewDemo": "View demo",
    "supply.viewGithub": "View on GitHub",
    "supply.section.overview": "Overview",
    "supply.section.agents": "AI Agents",
    "supply.section.stack": "Architecture",
    "supply.section.features": "Features",
    "supply.overview.title": "Real-Time Dashboard",
    "supply.overview.description": "Complete supply chain intelligence platform with predictive analytics and conversational AI agents.",
    "supply.overview.detail1": "6 specialized AI agents (Dust.tt) for multi-domain analysis",
    "supply.overview.detail2": "NL2SQL: natural language questions to SQL queries",
    "supply.overview.detail3": "Interactive visualizations (Recharts, Leaflet)",
    "supply.agents.title": "6 Specialized AI Agents",
    "supply.agents.monitoring": "Monitoring",
    "supply.agents.monitoring.desc": "Sales and marketplace trends analysis",
    "supply.agents.supply": "Supply Allocation",
    "supply.agents.supply.desc": "ABC analysis, HHI concentration",
    "supply.agents.pricing": "Pricing Adjustment",
    "supply.agents.pricing.desc": "Stock rotation, DSI, dormant items",
    "supply.agents.eco": "EcoFlow Analyst",
    "supply.agents.eco.desc": "CO2 footprint, logistics score",
    "supply.agents.predictive": "Predictive AI",
    "supply.agents.predictive.desc": "Stockout forecasts, alerts",
    "supply.agents.orchestrator": "Orchestrator",
    "supply.agents.orchestrator.desc": "Multi-agent delegation",
    "supply.stack.title": "Technical Architecture",
    "supply.stack.frontend": "Frontend",
    "supply.stack.backend": "Backend / Services",
    "supply.stack.database": "Database",
    "supply.features.title": "Dashboard Views",
    "supply.features.overview": "Overview View",
    "supply.features.products": "Products View",
    "supply.features.financial": "Financial View",
    "supply.features.sustainability": "Sustainability View",
    "supply.features.predictive": "Predictive View",
    "supply.features.analysis": "AI Analysis View",
    
    // Mario Kart Page
    "mario.badge": "Data Project",
    "mario.title": "Mario Kart World Records",
    "mario.description": "Control the car with arrow keys or by clicking to discover the web scraping project of Mario Kart 8 world records",
    "mario.startRace": "Start the race",
    "mario.restart": "Restart",
    "mario.continue": "Continue",
    "mario.finish": "Finish",
    "mario.controls": "Controls",
    "mario.controlsDesc": "Left/right arrows or click on sides",
    "mario.checkpoint.context": "Context",
    "mario.checkpoint.demo": "Demo",
    "mario.checkpoint.presentation": "Presentation",
    "mario.context.title": "Mario Kart 8 Web Scraping",
    "mario.context.description": "Extraction and analysis of Mario Kart 8 world records from Mario Kart World Records website.",
    "mario.context.detail1": "Scraping of record times on all tracks",
    "mario.context.detail2": "Extraction of player, vehicle and configuration data",
    "mario.context.detail3": "Goal: Identify the best competitive meta and strategies",
    "mario.demo.title": "Scraping Demo",
    "mario.demo.description": "This video shows the scraping process in action. The script extracts data and generates a CSV file containing all cleaned and structured information.",
    "mario.demo.csvOutput": "CSV export with cleaned data",
    "mario.presentation.title": "Project Presentation",
    "mario.presentation.description": "Discover the complete data analysis, insights and results in the Canva presentation.",
    "mario.presentation.view": "View presentation",
    "mario.tech.title": "Tech Stack",
    "mario.tech.used": "Technologies used",
    "mario.tech.files": "Main files",
    "mario.results.title": "Project Results",
    "mario.results.execTime": "Execution time",
    "mario.results.dataExtracted": "Data extracted",
    "mario.results.realtime": "Real-time",
    "mario.sourceCode": "Source code",
    "mario.viewResults": "View results",
    "mario.raceComplete": "Race complete!",
    "mario.raceCompleteDesc": "You have discovered all aspects of the Mario Kart World Records project",
    "mario.viewGithub": "View on GitHub",
    "mario.replay": "Replay",
    
    // ZigZag Page
    "zigzag.badge": "Drawing Mini-Game",
    "zigzag.title": "ZigZag",
    "zigzag.description": "Reproduce the drawings to discover the project! Inspired by Gartic Phone, draw and move to the next level.",
    "zigzag.level": "Level",
    "zigzag.tutorial": "Tutorial",
    "zigzag.intermediate": "Intermediate",
    "zigzag.challenger": "Challenger",
    "zigzag.play": "Start",
    "zigzag.restart": "Restart",
    "zigzag.clear": "Clear",
    "zigzag.submit": "Submit",
    "zigzag.drawThis": "Draw this:",
    "zigzag.yourDrawing": "Your drawing:",
    "zigzag.wellDone": "Well done!",
    "zigzag.levelComplete": "Level {level} complete!",
    "zigzag.nextLevel": "Next level",
    "zigzag.replay": "Replay",
    "zigzag.projectLinks": "Project links",
    "zigzag.playOnSite": "Play on zig-zag.fun",
    "zigzag.viewSource": "View source code",
    "zigzag.progress": "Progress",
    "zigzag.info1.title": "ZigZag - Multiplayer Drawing Game",
    "zigzag.info1.description": "Online multiplayer game inspired by Gartic Phone. Players draw and guess in chain for guaranteed fun moments!",
    "zigzag.info2.title": "Tech Stack",
    "zigzag.info2.description": "Modern application with Google OAuth authentication and real-time sync via Supabase.",
    "zigzag.info3.title": "Features",
    "zigzag.info3.description": "Complete experience with lobbies, game rounds, and drawing gallery. Deployed in production.",
    "zigzag.technologies": "Technologies",
    "zigzag.features": "Features",
    "zigzag.realtime": "Real-time",
    "zigzag.auth": "Google OAuth",
    "zigzag.deployed": "Deployed on zig-zag.fun",
    
    // Synapse Page
    "synapse.badge": "RAG Chatbot",
    "synapse.title": "Synapse",
    "synapse.subtitle": "RAG Chatbot for Scientific Research",
    "synapse.description": "Communication between data and artificial intelligence. Explore 182K+ French theses with contextual Q&A.",
    "synapse.viewGithub": "View on GitHub",
    "synapse.explore": "Explore",
    "synapse.openBook": "Open the book",
    "synapse.page": "Page",
    "synapse.nextPage": "Next page",
    "synapse.prevPage": "Previous page",
    "synapse.closeBook": "Close book",
    "synapse.featuresTitle": "Features",
    "synapse.featuresSubtitle": "Three pillars for intelligent research",
    "synapse.feature1.title": "HAL Search",
    "synapse.feature1.description": "Access to 182K+ French theses via HAL API",
    "synapse.feature2.title": "RAG Chat",
    "synapse.feature2.description": "Contextual Q&A with citations",
    "synapse.feature3.title": "ML Features",
    "synapse.feature3.description": "Classification, summaries, recommendations",
    "synapse.stackTitle": "Tech Stack",
    "synapse.stackSubtitle": "Modern technologies for a robust architecture",
    "synapse.backend": "Backend",
    "synapse.frontend": "Frontend",
    "synapse.database": "Database",
    "synapse.pipelineTitle": "RAG Pipeline",
    "synapse.pipelineSubtitle": "From question to contextualized answer",
    "synapse.pipeline.request": "Request",
    "synapse.pipeline.api": "HAL API",
    "synapse.pipeline.extraction": "PDF Extraction",
    "synapse.pipeline.vectorization": "Vectorization",
    "synapse.pipeline.chat": "Chat",
    "synapse.pipeline.response": "Response",
    "synapse.ctaTitle": "Explore the project",
    "synapse.ctaDescription": "Discover the source code, documentation and contribute to Synapse development on GitHub.",
    
    // About Page
    "about.badge": "About",
    "about.title": "Aurelie Perichon",
    "about.subtitle": "Business and technical profile in AI and data, I design solutions that make analysis clearer, automate useful workflows and support decision-making.",
    "about.contact": "Contact",
    "about.languages": "Languages",
    "about.french": "French",
    "about.english": "English",
    "about.native": "Native",
    "about.interests": "Interests",
    "about.interest.gaming": "Video games",
    "about.interest.singing": "Singing",
    "about.interest.asian": "Asian culture",
    "about.interest.climbing": "Climbing",
    "about.interest.dance": "Dance",
    "about.interest.travel": "Travel",
    "about.profile": "Profile",
    "about.profileText": "Business and technical profile in AI and data, I design solutions that make analysis clearer, automate useful workflows and support decision-making.",
    "about.education": "Education",
    "about.current": "Current",
    "about.experience": "Experience",
    "about.skills": "Skills",
    "about.ctaTitle": "Interested in my profile?",
    "about.ctaDescription": "Feel free to contact me to discuss projects or opportunities.",
    "about.contactMe": "Contact me",
    
    // Footer
    "footer.description": "MSc AI Applied to Business student, passionate about data analysis to drive strategy and innovation.",
    "footer.projects": "Projects",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.supplyBrain": "Supply Brain - Mirakl Hackathon",
    "footer.synapse": "Synapse - RAG Chatbot",
    "footer.eugenia": "Eugenia School - SEO/GEO",
    "footer.zigzag": "ZigZag - Mini-Game",
    "footer.marioKart": "Mario Kart - Web Scraping",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("fr")

  useEffect(() => {
    const saved = localStorage.getItem("portfolio-language") as Language
    if (saved && (saved === "fr" || saved === "en")) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("portfolio-language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
